global:                                                                         
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:                                                              
      monitor: 'exporter-metrics'                                                
                                                                                
scrape_configs:

- job_name: 'HostsMetrics'
  dns_sd_configs:
  - names:
    - node-exporter
    refresh_interval: 15s
    type: A
    port: 9100

- job_name: 'ContainerMetrics'
  static_configs:
    - targets:
      - 'rancher-server:9108'

- job_name: 'RancherServerMetrics'
  dns_sd_configs:
  - names:
    - cadvisor
    refresh_interval: 15s
    type: A
    port: 8080

- job_name: 'RancherApi'
  dns_sd_configs:
  - names:
    - 'prometheus-rancher-exporter'
    refresh_interval: 15s
    type: A
    port: 9173

- job_name: 'Prometheus'
  static_configs:
    - targets:
      - '127.0.0.1:9090'

- job_name: 'HAProxy'
  dns_sd_configs:
  - names:
    - 'haproxy-exporter'
    refresh_interval: 15s
    type: A
    port: 9101

- job_name: 'WebAPI'
  dns_sd_configs:
  - names:
    - 'web-api-exporter'
    refresh_interval: 15s
    type: A
    port: 3000

- job_name: 'Postgres'
  dns_sd_configs:
  - names:
    - 'postgres-exporter'
    refresh_interval: 15s
    type: A
    port: 9187
